name: 'Codebase Snapshot Action'
description: 'Creates a codebase snapshot archive, finds a Seal entity by PR#, uploads the archive to Seal, and links it to the entity.'
author: 'Seal' 

inputs:
  seal_api_token:
    description: 'Seal API Token'
    required: true
  seal_api_base_url:
    description: 'Seal API Base URL (e.g., https://us.backend.seal.run/api/)'
    required: true
  seal_template_id:
    description: 'Seal Template ID for the target change control entity'
    required: true
  seal_snapshot_field_name:
     description: 'Name of the reference field in the Seal entity to link the snapshot'
     required: false
     default: 'Code Snapshot'
  seal_file_type_title:
     description: 'Title for the uploaded file type in Seal (e.g., "GitHub Artifacts")'
     required: false
     default: 'GitHub Artifacts'
  exclude_patterns:
    description: 'Space-separated glob patterns to exclude from the archive (e.g., ".git/* node_modules/*").'
    required: false
  archive_type:
    description: 'The type of archive to create (supported: zip, tar).'
    required: false
    default: 'zip'

runs:
  using: 'composite'
  steps:
    - name: Install Runtime Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends zip tar
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Action Script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env: 
        INPUT_SEAL_API_TOKEN: ${{ inputs.seal_api_token }}
        INPUT_SEAL_API_BASE_URL: ${{ inputs.seal_api_base_url }}
        INPUT_SEAL_TEMPLATE_ID: ${{ inputs.seal_template_id }}
        INPUT_SEAL_SNAPSHOT_FIELD_NAME: ${{ inputs.seal_snapshot_field_name }}
        INPUT_SEAL_FILE_TYPE_TITLE: ${{ inputs.seal_file_type_title }}
        INPUT_EXCLUDE_PATTERNS: ${{ inputs.exclude_patterns }}
        INPUT_ARCHIVE_TYPE: ${{ inputs.archive_type }}

branding:
  icon: 'archive'
  color: 'blue'
