name: Codebase Snapshot via Uses 

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  pull-requests: read

jobs:
  codebase_snapshot_via_uses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4

      - name: Run Codebase Snapshot Action
        uses: opvia/seal-github-actions/.github/actions/codebase-snapshot@main
        with:
          seal_api_token: ${{ secrets.SEAL_API_TOKEN }}
          seal_api_base_url: 'https://us.backend.seal.run/api/'
          seal_template_id: '3eecf18f-da15-429c-968a-df43ba85c970'
          seal_snapshot_field_name: 'Code Snapshot'
          seal_file_type_title: 'GitHub-Artifacts'
          exclude_patterns: '.git/*'
          archive_type: 'zip'

      - name: Upload Complete Check
        if: always()
        run: echo "Codebase snapshot action finished attempt."
