name: Codebase Snapshot via Image

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read        
  pull-requests: read  
  packages: read      

jobs:
  codebase_snapshot_via_image:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout code (of the repo using the action)
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Step 2: Run the published Docker container action
      - name: Create and Upload Seal Snapshot
        uses: docker://ghcr.io/opvia/codebase-snapshot-action:latest # Or version 
        with:
          seal_api_token: ${{ secrets.SEAL_API_TOKEN }} 
          seal_api_base_url: 'https://us.backend.seal.run/api/'
          seal_template_id: '3eecf18f-da15-429c-968a-df43ba85c970'
          seal_snapshot_field_name: 'Code Snapshot' 
          seal_file_type_title: 'GitHub-Artifacts'   

          exclude_patterns: '.git/*' 
          archive_type: 'zip'
