name: Create Seal Snapshot on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read        
  pull-requests: read  
  packages: read      

jobs:
  create_snapshot:
    if: startsWith(github.head_ref, 'rc/') && contains(github.base_ref, 'r') 
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout code so the action can access it
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Set to 0 to get all history

      # Step 2: Run the published Docker container action
      - name: Create and Upload Seal Snapshot
        uses: docker://ghcr.io/opvia/codebase-snapshot-action:v1.0.2 # Or latest 
        with:
          seal_api_token: ${{ secrets.SEAL_API_TOKEN }} # Add api key to repo secrets
          seal_api_base_url: 'https://us.backend.seal.run/api/'
          seal_template_id: '3eecf18f-da15-429c-968a-df43ba85c970'
          seal_snapshot_field_name: 'Code Snapshot' 
          seal_file_type_title: 'GitHub-Artifacts'   

          exclude_patterns: '.git/*' 
          archive_type: 'zip'

      # Optional: Add post snapshot steps
      - name: Post Snapshot Step (Example)
        if: always()
        run: echo "Snapshot action completed."
