name: Upload Release Artifacts via Uses Syntax

on:
  pull_request: 
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read       
  pull-requests: read  

jobs:
  upload_via_uses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4

      - name: Upload Artifacts to Seal
        uses: opvia/seal-github-actions/.github/actions/upload-artifacts@main
        with:
          seal_api_token: ${{ secrets.SEAL_API_TOKEN }}
          seal_api_base_url: 'https://us.backend.seal.run/api/'
          seal_template_id: '3eecf18f-da15-429c-968a-df43ba85c970'
          seal_field_name: 'Release Artifact(s)'
          seal_file_type_title: 'GitHub-Artifacts'
          artifact_patterns: '"*/README.md"'
