name: Upload Release Artifacts via Checkout

on:
  pull_request: 
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read       
  pull-requests: read  

jobs:
  upload_via_checkout:
    runs-on: ubuntu-latest # replace with any runner

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Main Repo
        uses: actions/checkout@v4

      # Step 2: Checkout the action's source code into a specific path
      - name: Checkout upload-artifacts Action Code
        uses: actions/checkout@v4
        with:
          repository: opvia/seal-github-actions
          # Checkout into a subdirectory to avoid conflicts
          path: ./action-src/upload-artifacts
          # Optional: Pin to a specific tag or commit SHA
          ref: v1.0.0

      # Step 3: Setup Node.js environment (required by the TS action)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match the version used by the action

      # Step 4: Execute the compiled entrypoint script directly using node
      # IMPORTANT: Assumes the 'dist/index.js' file exists in the checked-out action code.
      - name: Run Upload Artifacts Script 
        run: node ./action-src/upload-artifacts/dist/index.js
        shell: bash
        env:
          INPUT_SEAL_API_TOKEN: ${{ secrets.SEAL_API_TOKEN }}
          INPUT_SEAL_API_BASE_URL: 'https://us.backend.seal.run/api/'
          INPUT_SEAL_TEMPLATE_ID: '3eecf18f-da15-429c-968a-df43ba85c970'

          INPUT_SEAL_FIELD_NAME: 'Release Artifact(s)'
          INPUT_SEAL_FILE_TYPE_TITLE: 'GitHub-Artifacts'
          INPUT_ARTIFACT_PATTERNS: '"*/README.md"' # Example patterns

      - name: Upload Complete Check
        if: always() 
        run: echo "Upload artifacts script finished attempt."
